{
 "title": "MeasurementVisualization",
 "time": { "from": "2025-04-18T09:49:23.000Z", "to": "2025-04-18T09:49:24.349Z" },
 "panels": [
  {
   "title": "Unsynchronisierte Daten",
   "type": "timeseries",
   "description": "bucket: daten-roh",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"daten-roh\")\r\n  |> range(start: 2025-04-18T09:49:23.00Z, stop: 2025-04-18T09:49:24.35Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inserterdTestData_short29\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Sync_Signal\" or r[\"_field\"] == \"sync_signal\")\r\n"
    }
   ]
  },
  {
   "title": "Sensordaten",
   "type": "timeseries",
   "description": "Ein beispielhafter Channel\nbucket: daten-roh",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"daten-roh\")\r\n  |> range(start: 2025-04-18T09:46:01Z, stop: 2025-04-18T09:46:04Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data_01\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"yForce\")\r\n"
    }
   ]
  },
  {
   "title": "Synchronisierte Daten",
   "type": "timeseries",
   "description": "bucket: daten-aufbereitet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"daten-aufbereitet\")\r\n  |> range(start: 2025-04-18T09:53:08Z, stop: 2025-04-18T09:53:10Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inserterdTestData_short29\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Sync_Signal\" or r[\"_field\"] == \"sync_signal\")\r\n"
    }
   ]
  },
  {
   "title": "Metadaten Sensoren",
   "type": "table",
   "description": "bucket: daten-roh",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"daten-roh\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) =>\r\n    r[\"_measurement\"] == \"sensor_data_01\" and\r\n    r[\"dataType\"]      == \"matlabMetadata\"\r\n  )\r\n  // unnötige Influx-Spalten entfernen\r\n  |> drop(columns: [\"_measurement\", \"_field\"])\r\n  // alle Daten in eine Gruppe zusammenfassen\r\n  |> group()\r\n  // Pivotieren: pro Kombination aus deinen Tags eine Zeile,\r\n  // und pro Datum eine Spalte mit dem Messwert\r\n  |> pivot(\r\n    rowKey:      [\"channelNumber\", \"einheit\", \"notizen\", \"measuredQuantity\", \"messrichtung\"],\r\n    columnKey:   [\"_time\"],\r\n    valueColumn: \"_value\"\r\n  )\r\n  // Zeit‑Metainfos weghauen\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\"])\r\n"
    }
   ]
  }
 ]
}