
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=daten-roh
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    volumes:
      - influxdb-data:/var/lib/influxdb2
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  http_to_mqtt_service:
    image: http-to-mqtt
    container_name: http_to_mqtt_service
    ports:
      - "9900:9910" # Externer Port für deinen HTTP-Endpunkt
    depends_on:
      - mosquitto

  synchronize_matlab_edge_data:
    image: synchronize-matlab-edge-data
    container_name: synchronize_matlab_edge_data
    ports:
      - "9902:9910"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influxdb
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  proxy:
    build:
      context: ./proxy  # Zeigt auf den Proxy-Ordner
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "5050:5000"  # Proxy läuft auf Port 5000
    restart: always
    depends_on:
      - http_to_mqtt_service

volumes:
  influxdb-data:
  grafana-storage:
