%% Konfiguration
% InfluxDB-Write URL inklusive Precision (ns) und Bucket/Org
influxURL = 'http://localhost:8086/api/v2/write?org=4c0bacdd5f5d7868&bucket=daten-aufbereitet&precision=ns';
token     = 'R-Klt0c_MSuLlVJwvDRWItqX40G_ATERJvr4uy93xgYe1d7MoyHIY_sc_twi4h6GnQdmU9WJI74NbwntEI2luw==';

%% Payload vorbereiten: Erstelle 5 Messpunkte mit aktuellen Timestamps
% Hole den aktuellen Zeitstempel in Nanosekunden:
nowNs = posixtime(datetime('now')) * 1e9 -3600 *1e9;
% Erstelle Messpunkte: Jeder Punkt erhält einen Zeitoffset von 1 Sekunde (1e9 ns)
payload = sprintf(['measurement value=0 %0.0f\n' ...
                   'measurement value=1 %0.0f\n' ...
                   'measurement value=2 %0.0f\n' ...
                   'measurement value=3 %0.0f\n' ...
                   'measurement value=4 %0.0f'], ...
                   nowNs, nowNs+1e9, nowNs+2e9, nowNs+3e9, nowNs+4e9);

%% Weboptions konfigurieren
options = weboptions(...
    'RequestMethod', 'post', ...
    'MediaType', 'text/plain', ...
    'HeaderFields', { ...
        'Authorization', ['Token ' token]; ...
        'Content-Type', 'text/plain; charset=utf-8'} ...
    );

%% Anfrage senden
try
    fprintf('Sende Write-Anfrage an InfluxDB...\n');
    response = webwrite(influxURL, payload, options);
    fprintf('Antwort erhalten:\n');
    disp(response);
catch ME
    fprintf('Fehler bei der Anfrage: %s\n', ME.message);
    response = [];
end
